import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";
import LoadingSpinner from "~/components/LoadingSpinner";
import Link from "next/link";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();
  // Move to getById after finishing functionality
  // const { data, isLoading } = api.emotionEvent.getById.useQuery({id: user});

  const { data, isLoading } = api.emotionEvent.getMostCommonEmotions.useQuery();

  const [showingModal, isShowingModal] = useState<boolean>(false);

  if (isLoading) {
    return (
      <div className="flex h-screen w-full items-center justify-center">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Emotion Diary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col items-center">
        <div className="flex h-screen flex-col w-full">
          <div className="flex justify-between p-5">
            <Link href={"/"}>
            Home
            </Link>
            {isSignedIn ? <SignOutButton /> : <SignInButton />}
          </div>
          <div className="relative flex-1 flex flex-col justify-center items-center">
            <div className="bg-slate-200 p-48">
                Top ten most frequent emotions
                {data?.map((value) => {
                  return(
                  <div>{value.emotion}, {value.count}</div>)
                })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
