import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";
import LoadingSpinner from "~/components/LoadingSpinner";
import Link from "next/link";
import { DoughnutChart } from "~/components/Analysis/DoughnutChart";

const Analysis: NextPage = () => {
  const { isSignedIn, user } = useUser();

  const { data : commonEmotions, isLoading } = api.emotionEvent.getMostCommonEmotions.useQuery();
  const { data : commonPsymptoms } = api.emotionEvent.getMostCommonPSymptoms.useQuery();

  

  if (isLoading) {
    return (
      <div className="flex h-screen w-full items-center justify-center">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Emotion Diary</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col items-center">
        <div className="flex h-screen flex-col w-full">
          <div className="flex justify-between p-5">
            <Link href={"/"}>
            Home
            </Link>
            {isSignedIn ? <SignOutButton /> : <SignInButton />}
          </div>
          <div className="relative flex-1 flex justify-evenly items-center">
            <div className="bg-slate-200 p-24 text-center">
                Your most common emotions
                {commonEmotions && <DoughnutChart labels={commonEmotions.map((entry) => entry.emotion)} values={commonEmotions.map((entry) => entry.count)}/>}
            </div>
            <div className="bg-slate-200 p-24 text-center">
                Your most common physical symptoms
                {commonPsymptoms && <DoughnutChart labels={commonPsymptoms.map((entry) => entry.psymptom)} values={commonPsymptoms.map((entry) => entry.count)}/>}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Analysis;
